"""initial tables

Revision ID: 176ef7ffb56b
Revises: 
Create Date: 2026-03-12 22:03:33.336103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176ef7ffb56b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('max_stock', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('max_stock', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=30), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplies_category'), 'supplies', ['category'], unique=False)
    op.create_index(op.f('ix_supplies_id'), 'supplies', ['id'], unique=False)
    op.create_index(op.f('ix_supplies_name'), 'supplies', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_records_id'), 'weather_records', ['id'], unique=False)
    op.create_index(op.f('ix_weather_records_weather_date'), 'weather_records', ['weather_date'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('movement_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_supply_id'), 'inventory_movements', ['supply_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_user_id'), 'inventory_movements', ['user_id'], unique=False)
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_produced', sa.Float(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('batch', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_batch'), 'productions', ['batch'], unique=False)
    op.create_index(op.f('ix_productions_id'), 'productions', ['id'], unique=False)
    op.create_index(op.f('ix_productions_product_id'), 'productions', ['product_id'], unique=False)
    op.create_index(op.f('ix_productions_user_id'), 'productions', ['user_id'], unique=False)
    op.create_table('recipe_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('supply_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'supply_id', name='uq_recipe_product_supply')
    )
    op.create_index(op.f('ix_recipe_details_id'), 'recipe_details', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_details_product_id'), 'recipe_details', ['product_id'], unique=False)
    op.create_index(op.f('ix_recipe_details_supply_id'), 'recipe_details', ['supply_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_time', sa.Time(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sales_channel', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_user_id'), 'sales', ['user_id'], unique=False)
    op.create_table('sale_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_details_id'), 'sale_details', ['id'], unique=False)
    op.create_index(op.f('ix_sale_details_product_id'), 'sale_details', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_details_sale_id'), 'sale_details', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_details_sale_id'), table_name='sale_details')
    op.drop_index(op.f('ix_sale_details_product_id'), table_name='sale_details')
    op.drop_index(op.f('ix_sale_details_id'), table_name='sale_details')
    op.drop_table('sale_details')
    op.drop_index(op.f('ix_sales_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_recipe_details_supply_id'), table_name='recipe_details')
    op.drop_index(op.f('ix_recipe_details_product_id'), table_name='recipe_details')
    op.drop_index(op.f('ix_recipe_details_id'), table_name='recipe_details')
    op.drop_table('recipe_details')
    op.drop_index(op.f('ix_productions_user_id'), table_name='productions')
    op.drop_index(op.f('ix_productions_product_id'), table_name='productions')
    op.drop_index(op.f('ix_productions_id'), table_name='productions')
    op.drop_index(op.f('ix_productions_batch'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_inventory_movements_user_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_supply_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_weather_records_weather_date'), table_name='weather_records')
    op.drop_index(op.f('ix_weather_records_id'), table_name='weather_records')
    op.drop_table('weather_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplies_name'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_id'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_category'), table_name='supplies')
    op.drop_table('supplies')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
